// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v7.34.0
// source: wire.proto

package wirepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FolderType is the reserved direction/trust shape (the clean BEP set). M3
// populates only the send-receive default; direction (M4) and receive-encrypted
// (M6) ride this field later.
type FolderType int32

const (
	FolderType_FOLDER_TYPE_SEND_RECEIVE      FolderType = 0
	FolderType_FOLDER_TYPE_SEND_ONLY         FolderType = 1
	FolderType_FOLDER_TYPE_RECEIVE_ONLY      FolderType = 2
	FolderType_FOLDER_TYPE_RECEIVE_ENCRYPTED FolderType = 3
)

// Enum value maps for FolderType.
var (
	FolderType_name = map[int32]string{
		0: "FOLDER_TYPE_SEND_RECEIVE",
		1: "FOLDER_TYPE_SEND_ONLY",
		2: "FOLDER_TYPE_RECEIVE_ONLY",
		3: "FOLDER_TYPE_RECEIVE_ENCRYPTED",
	}
	FolderType_value = map[string]int32{
		"FOLDER_TYPE_SEND_RECEIVE":      0,
		"FOLDER_TYPE_SEND_ONLY":         1,
		"FOLDER_TYPE_RECEIVE_ONLY":      2,
		"FOLDER_TYPE_RECEIVE_ENCRYPTED": 3,
	}
)

func (x FolderType) Enum() *FolderType {
	p := new(FolderType)
	*p = x
	return p
}

func (x FolderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FolderType) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_proto_enumTypes[0].Descriptor()
}

func (FolderType) Type() protoreflect.EnumType {
	return &file_wire_proto_enumTypes[0]
}

func (x FolderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FolderType.Descriptor instead.
func (FolderType) EnumDescriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{0}
}

// Hello is the first frame each peer sends, before authorization. It rides in a
// magic-prefixed envelope (see the framing layer), not under Header.
type Hello struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	WireFormatVersion uint32                 `protobuf:"varint,2,opt,name=wire_format_version,json=wireFormatVersion,proto3" json:"wire_format_version,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ClientName        string                 `protobuf:"bytes,4,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientVersion     string                 `protobuf:"bytes,5,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_wire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Hello) GetWireFormatVersion() uint32 {
	if x != nil {
		return x.WireFormatVersion
	}
	return 0
}

func (x *Hello) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hello) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *Hello) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

// Header precedes every post-Hello message body on the control stream. It carries
// the body's type so a peer can route without parsing it, and the codec used to
// compress the body so it can be decompressed without parsing it.
type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Compression   uint32                 `protobuf:"varint,2,opt,name=compression,proto3" json:"compression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_wire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{1}
}

func (x *Header) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Header) GetCompression() uint32 {
	if x != nil {
		return x.Compression
	}
	return 0
}

// Folder is one folder a peer offers in its NetworkConfig. Folders match across
// nodes solely by folder_id (the shared string agreed at pairing), independent of
// the encryption key. Tags 4-6 are reserved for the M4 resync cursor
// (index_epoch_id, high_water_sequence) and the M6 key-agreement token
// (encryption_password_token).
type Folder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	FolderType    FolderType             `protobuf:"varint,2,opt,name=folder_type,json=folderType,proto3,enum=trove.wire.v1.FolderType" json:"folder_type,omitempty"`
	Encrypted     bool                   `protobuf:"varint,3,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Folder) Reset() {
	*x = Folder{}
	mi := &file_wire_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Folder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Folder) ProtoMessage() {}

func (x *Folder) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Folder.ProtoReflect.Descriptor instead.
func (*Folder) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{2}
}

func (x *Folder) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *Folder) GetFolderType() FolderType {
	if x != nil {
		return x.FolderType
	}
	return FolderType_FOLDER_TYPE_SEND_RECEIVE
}

func (x *Folder) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

// NetworkConfig is the first post-Hello message, sent exactly once each way. The
// connection's shared-folder set is the intersection of both sides' folder_ids.
// Tag 3 is reserved for advertised addresses (address gossip).
type NetworkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folders       []*Folder              `protobuf:"bytes,1,rep,name=folders,proto3" json:"folders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_wire_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkConfig) GetFolders() []*Folder {
	if x != nil {
		return x.Folders
	}
	return nil
}

// Ping is the idle-timer keepalive.
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_wire_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{4}
}

// Close requests a graceful shutdown.
type Close struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Close) Reset() {
	*x = Close{}
	mi := &file_wire_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Close) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Close) ProtoMessage() {}

func (x *Close) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Close.ProtoReflect.Descriptor instead.
func (*Close) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{5}
}

func (x *Close) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_wire_proto protoreflect.FileDescriptor

const file_wire_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"wire.proto\x12\rtrove.wire.v1\"\xac\x01\n" +
	"\x05Hello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12.\n" +
	"\x13wire_format_version\x18\x02 \x01(\rR\x11wireFormatVersion\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vclient_name\x18\x04 \x01(\tR\n" +
	"clientName\x12%\n" +
	"\x0eclient_version\x18\x05 \x01(\tR\rclientVersion\">\n" +
	"\x06Header\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12 \n" +
	"\vcompression\x18\x02 \x01(\rR\vcompression\"\x91\x01\n" +
	"\x06Folder\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\x12:\n" +
	"\vfolder_type\x18\x02 \x01(\x0e2\x19.trove.wire.v1.FolderTypeR\n" +
	"folderType\x12\x1c\n" +
	"\tencrypted\x18\x03 \x01(\bR\tencryptedJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\x06\x10\a\"F\n" +
	"\rNetworkConfig\x12/\n" +
	"\afolders\x18\x01 \x03(\v2\x15.trove.wire.v1.FolderR\afoldersJ\x04\b\x03\x10\x04\"\x06\n" +
	"\x04Ping\"\x1f\n" +
	"\x05Close\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason*\x86\x01\n" +
	"\n" +
	"FolderType\x12\x1c\n" +
	"\x18FOLDER_TYPE_SEND_RECEIVE\x10\x00\x12\x19\n" +
	"\x15FOLDER_TYPE_SEND_ONLY\x10\x01\x12\x1c\n" +
	"\x18FOLDER_TYPE_RECEIVE_ONLY\x10\x02\x12!\n" +
	"\x1dFOLDER_TYPE_RECEIVE_ENCRYPTED\x10\x03B@Z>github.com/GhentiLabs/Trove/client/internal/wire/wirepb;wirepbb\x06proto3"

var (
	file_wire_proto_rawDescOnce sync.Once
	file_wire_proto_rawDescData []byte
)

func file_wire_proto_rawDescGZIP() []byte {
	file_wire_proto_rawDescOnce.Do(func() {
		file_wire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wire_proto_rawDesc), len(file_wire_proto_rawDesc)))
	})
	return file_wire_proto_rawDescData
}

var file_wire_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_wire_proto_goTypes = []any{
	(FolderType)(0),       // 0: trove.wire.v1.FolderType
	(*Hello)(nil),         // 1: trove.wire.v1.Hello
	(*Header)(nil),        // 2: trove.wire.v1.Header
	(*Folder)(nil),        // 3: trove.wire.v1.Folder
	(*NetworkConfig)(nil), // 4: trove.wire.v1.NetworkConfig
	(*Ping)(nil),          // 5: trove.wire.v1.Ping
	(*Close)(nil),         // 6: trove.wire.v1.Close
}
var file_wire_proto_depIdxs = []int32{
	0, // 0: trove.wire.v1.Folder.folder_type:type_name -> trove.wire.v1.FolderType
	3, // 1: trove.wire.v1.NetworkConfig.folders:type_name -> trove.wire.v1.Folder
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wire_proto_init() }
func file_wire_proto_init() {
	if File_wire_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wire_proto_rawDesc), len(file_wire_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_proto_goTypes,
		DependencyIndexes: file_wire_proto_depIdxs,
		EnumInfos:         file_wire_proto_enumTypes,
		MessageInfos:      file_wire_proto_msgTypes,
	}.Build()
	File_wire_proto = out.File
	file_wire_proto_goTypes = nil
	file_wire_proto_depIdxs = nil
}
