// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v7.34.0
// source: wire.proto

package wirepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FolderType is the reserved direction/trust shape (the clean BEP set). M3
// populates only the send-receive default; direction (M4) and receive-encrypted
// (M6) ride this field later.
type FolderType int32

const (
	FolderType_FOLDER_TYPE_SEND_RECEIVE      FolderType = 0
	FolderType_FOLDER_TYPE_SEND_ONLY         FolderType = 1
	FolderType_FOLDER_TYPE_RECEIVE_ONLY      FolderType = 2
	FolderType_FOLDER_TYPE_RECEIVE_ENCRYPTED FolderType = 3
)

// Enum value maps for FolderType.
var (
	FolderType_name = map[int32]string{
		0: "FOLDER_TYPE_SEND_RECEIVE",
		1: "FOLDER_TYPE_SEND_ONLY",
		2: "FOLDER_TYPE_RECEIVE_ONLY",
		3: "FOLDER_TYPE_RECEIVE_ENCRYPTED",
	}
	FolderType_value = map[string]int32{
		"FOLDER_TYPE_SEND_RECEIVE":      0,
		"FOLDER_TYPE_SEND_ONLY":         1,
		"FOLDER_TYPE_RECEIVE_ONLY":      2,
		"FOLDER_TYPE_RECEIVE_ENCRYPTED": 3,
	}
)

func (x FolderType) Enum() *FolderType {
	p := new(FolderType)
	*p = x
	return p
}

func (x FolderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FolderType) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_proto_enumTypes[0].Descriptor()
}

func (FolderType) Type() protoreflect.EnumType {
	return &file_wire_proto_enumTypes[0]
}

func (x FolderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FolderType.Descriptor instead.
func (FolderType) EnumDescriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{0}
}

// Hello is the first frame each peer sends, before authorization. It rides in a
// magic-prefixed envelope (see the framing layer), not under Header.
type Hello struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	WireFormatVersion uint32                 `protobuf:"varint,2,opt,name=wire_format_version,json=wireFormatVersion,proto3" json:"wire_format_version,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ClientName        string                 `protobuf:"bytes,4,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientVersion     string                 `protobuf:"bytes,5,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_wire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Hello) GetWireFormatVersion() uint32 {
	if x != nil {
		return x.WireFormatVersion
	}
	return 0
}

func (x *Hello) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hello) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *Hello) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

// Header precedes every post-Hello message body on the control stream. It carries
// the body's type so a peer can route without parsing it, and the codec used to
// compress the body so it can be decompressed without parsing it.
type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Compression   uint32                 `protobuf:"varint,2,opt,name=compression,proto3" json:"compression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_wire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{1}
}

func (x *Header) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Header) GetCompression() uint32 {
	if x != nil {
		return x.Compression
	}
	return 0
}

// Folder is one folder a peer offers in its NetworkConfig. Folders match across
// nodes solely by folder_id (the shared string agreed at pairing), independent of
// the encryption key. Tag 6 is reserved for the M6 key-agreement token
// (encryption_password_token).
type Folder struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FolderId          string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	FolderType        FolderType             `protobuf:"varint,2,opt,name=folder_type,json=folderType,proto3,enum=trove.wire.v1.FolderType" json:"folder_type,omitempty"`
	Encrypted         bool                   `protobuf:"varint,3,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	IndexEpochId      uint64                 `protobuf:"varint,4,opt,name=index_epoch_id,json=indexEpochId,proto3" json:"index_epoch_id,omitempty"`
	HighWaterSequence int64                  `protobuf:"varint,5,opt,name=high_water_sequence,json=highWaterSequence,proto3" json:"high_water_sequence,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Folder) Reset() {
	*x = Folder{}
	mi := &file_wire_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Folder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Folder) ProtoMessage() {}

func (x *Folder) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Folder.ProtoReflect.Descriptor instead.
func (*Folder) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{2}
}

func (x *Folder) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *Folder) GetFolderType() FolderType {
	if x != nil {
		return x.FolderType
	}
	return FolderType_FOLDER_TYPE_SEND_RECEIVE
}

func (x *Folder) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

func (x *Folder) GetIndexEpochId() uint64 {
	if x != nil {
		return x.IndexEpochId
	}
	return 0
}

func (x *Folder) GetHighWaterSequence() int64 {
	if x != nil {
		return x.HighWaterSequence
	}
	return 0
}

// NetworkConfig is the first post-Hello message, sent exactly once each way. The
// connection's shared-folder set is the intersection of both sides' folder_ids.
// Tag 3 is reserved for advertised addresses (address gossip).
type NetworkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folders       []*Folder              `protobuf:"bytes,1,rep,name=folders,proto3" json:"folders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_wire_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkConfig) GetFolders() []*Folder {
	if x != nil {
		return x.Folders
	}
	return nil
}

// FolderSummary is the owner's per-folder anti-entropy announcement on the control
// stream, sent once a session is Active and whenever the owner's folder root
// advances. A replica compares snapshot_root to its own and requests a delta if
// they differ; index_epoch_id and high_water_sequence drive the resync cursor.
type FolderSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FolderId          string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	SnapshotRoot      []byte                 `protobuf:"bytes,2,opt,name=snapshot_root,json=snapshotRoot,proto3" json:"snapshot_root,omitempty"`
	IndexEpochId      uint64                 `protobuf:"varint,3,opt,name=index_epoch_id,json=indexEpochId,proto3" json:"index_epoch_id,omitempty"`
	HighWaterSequence int64                  `protobuf:"varint,4,opt,name=high_water_sequence,json=highWaterSequence,proto3" json:"high_water_sequence,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FolderSummary) Reset() {
	*x = FolderSummary{}
	mi := &file_wire_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderSummary) ProtoMessage() {}

func (x *FolderSummary) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderSummary.ProtoReflect.Descriptor instead.
func (*FolderSummary) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{4}
}

func (x *FolderSummary) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *FolderSummary) GetSnapshotRoot() []byte {
	if x != nil {
		return x.SnapshotRoot
	}
	return nil
}

func (x *FolderSummary) GetIndexEpochId() uint64 {
	if x != nil {
		return x.IndexEpochId
	}
	return 0
}

func (x *FolderSummary) GetHighWaterSequence() int64 {
	if x != nil {
		return x.HighWaterSequence
	}
	return 0
}

// ManifestRequest asks the owner for every manifest with seq greater than
// since_sequence under the named epoch. since_sequence = 0 requests a full resync;
// an index_epoch_id that differs from the owner's also forces a full resync.
type ManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	IndexEpochId  uint64                 `protobuf:"varint,2,opt,name=index_epoch_id,json=indexEpochId,proto3" json:"index_epoch_id,omitempty"`
	SinceSequence int64                  `protobuf:"varint,3,opt,name=since_sequence,json=sinceSequence,proto3" json:"since_sequence,omitempty"`
	// since_chunk_offset resumes a manifest whose chunk list spans pages: the manifest at
	// the first sequence past since_sequence has had this many chunks delivered already.
	SinceChunkOffset int64 `protobuf:"varint,4,opt,name=since_chunk_offset,json=sinceChunkOffset,proto3" json:"since_chunk_offset,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ManifestRequest) Reset() {
	*x = ManifestRequest{}
	mi := &file_wire_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestRequest) ProtoMessage() {}

func (x *ManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestRequest.ProtoReflect.Descriptor instead.
func (*ManifestRequest) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{5}
}

func (x *ManifestRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *ManifestRequest) GetIndexEpochId() uint64 {
	if x != nil {
		return x.IndexEpochId
	}
	return 0
}

func (x *ManifestRequest) GetSinceSequence() int64 {
	if x != nil {
		return x.SinceSequence
	}
	return 0
}

func (x *ManifestRequest) GetSinceChunkOffset() int64 {
	if x != nil {
		return x.SinceChunkOffset
	}
	return 0
}

// ChunkRef is one ordered chunk reference within a manifest: the chunk identity and
// its plaintext length. Offsets are derived from the running length sum.
type ChunkRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       []byte                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Length        int64                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRef) Reset() {
	*x = ChunkRef{}
	mi := &file_wire_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRef) ProtoMessage() {}

func (x *ChunkRef) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRef.ProtoReflect.Descriptor instead.
func (*ChunkRef) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{6}
}

func (x *ChunkRef) GetChunkId() []byte {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *ChunkRef) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

// RemoteManifest carries one manifest in a delta with the owner's identity fields
// verbatim, so a replica stores it without minting its own version. manifest_id is
// re-verified against the chunk references on apply.
type RemoteManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          uint32                 `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	SymlinkTarget string                 `protobuf:"bytes,4,opt,name=symlink_target,json=symlinkTarget,proto3" json:"symlink_target,omitempty"`
	Chunks        []*ChunkRef            `protobuf:"bytes,5,rep,name=chunks,proto3" json:"chunks,omitempty"`
	ManifestId    []byte                 `protobuf:"bytes,6,opt,name=manifest_id,json=manifestId,proto3" json:"manifest_id,omitempty"`
	VersionVector []byte                 `protobuf:"bytes,7,opt,name=version_vector,json=versionVector,proto3" json:"version_vector,omitempty"`
	OwnerSequence int64                  `protobuf:"varint,8,opt,name=owner_sequence,json=ownerSequence,proto3" json:"owner_sequence,omitempty"`
	Deleted       bool                   `protobuf:"varint,9,opt,name=deleted,proto3" json:"deleted,omitempty"`
	DeletedMs     int64                  `protobuf:"varint,10,opt,name=deleted_ms,json=deletedMs,proto3" json:"deleted_ms,omitempty"`
	// more_chunks is set when this entry carries only a prefix of the file's chunk list and
	// the remainder continues in the following delta pages (same path and manifest_id).
	MoreChunks    bool `protobuf:"varint,11,opt,name=more_chunks,json=moreChunks,proto3" json:"more_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteManifest) Reset() {
	*x = RemoteManifest{}
	mi := &file_wire_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteManifest) ProtoMessage() {}

func (x *RemoteManifest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteManifest.ProtoReflect.Descriptor instead.
func (*RemoteManifest) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{7}
}

func (x *RemoteManifest) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *RemoteManifest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RemoteManifest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *RemoteManifest) GetSymlinkTarget() string {
	if x != nil {
		return x.SymlinkTarget
	}
	return ""
}

func (x *RemoteManifest) GetChunks() []*ChunkRef {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *RemoteManifest) GetManifestId() []byte {
	if x != nil {
		return x.ManifestId
	}
	return nil
}

func (x *RemoteManifest) GetVersionVector() []byte {
	if x != nil {
		return x.VersionVector
	}
	return nil
}

func (x *RemoteManifest) GetOwnerSequence() int64 {
	if x != nil {
		return x.OwnerSequence
	}
	return 0
}

func (x *RemoteManifest) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *RemoteManifest) GetDeletedMs() int64 {
	if x != nil {
		return x.DeletedMs
	}
	return 0
}

func (x *RemoteManifest) GetMoreChunks() bool {
	if x != nil {
		return x.MoreChunks
	}
	return false
}

// ManifestDelta is the owner's reply to a ManifestRequest: the changed manifests in
// owner-sequence order, plus the epoch and high-water they were taken at so the
// replica advances its cursor to exactly what it consumed.
type ManifestDelta struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FolderId          string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	IndexEpochId      uint64                 `protobuf:"varint,2,opt,name=index_epoch_id,json=indexEpochId,proto3" json:"index_epoch_id,omitempty"`
	HighWaterSequence int64                  `protobuf:"varint,3,opt,name=high_water_sequence,json=highWaterSequence,proto3" json:"high_water_sequence,omitempty"`
	Manifests         []*RemoteManifest      `protobuf:"bytes,4,rep,name=manifests,proto3" json:"manifests,omitempty"`
	// complete is false when more manifests remain past high_water_sequence; the
	// replica then requests the next page with since_sequence = high_water_sequence.
	Complete bool `protobuf:"varint,5,opt,name=complete,proto3" json:"complete,omitempty"`
	// high_water_chunk_offset is non-zero when the manifest at high_water_sequence is only
	// partially delivered; the next request resumes it at this chunk offset.
	HighWaterChunkOffset int64 `protobuf:"varint,6,opt,name=high_water_chunk_offset,json=highWaterChunkOffset,proto3" json:"high_water_chunk_offset,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ManifestDelta) Reset() {
	*x = ManifestDelta{}
	mi := &file_wire_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestDelta) ProtoMessage() {}

func (x *ManifestDelta) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestDelta.ProtoReflect.Descriptor instead.
func (*ManifestDelta) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{8}
}

func (x *ManifestDelta) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *ManifestDelta) GetIndexEpochId() uint64 {
	if x != nil {
		return x.IndexEpochId
	}
	return 0
}

func (x *ManifestDelta) GetHighWaterSequence() int64 {
	if x != nil {
		return x.HighWaterSequence
	}
	return 0
}

func (x *ManifestDelta) GetManifests() []*RemoteManifest {
	if x != nil {
		return x.Manifests
	}
	return nil
}

func (x *ManifestDelta) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *ManifestDelta) GetHighWaterChunkOffset() int64 {
	if x != nil {
		return x.HighWaterChunkOffset
	}
	return 0
}

// MembershipEntry is one signed roster record on the wire. The signature is over the
// membership layer's canonical hand-rolled bytes, not these protobuf bytes.
type MembershipEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Role          uint32                 `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	AddedBy       string                 `protobuf:"bytes,5,opt,name=added_by,json=addedBy,proto3" json:"added_by,omitempty"`
	AddedAtMs     int64                  `protobuf:"varint,6,opt,name=added_at_ms,json=addedAtMs,proto3" json:"added_at_ms,omitempty"`
	Sig           []byte                 `protobuf:"bytes,7,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipEntry) Reset() {
	*x = MembershipEntry{}
	mi := &file_wire_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipEntry) ProtoMessage() {}

func (x *MembershipEntry) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipEntry.ProtoReflect.Descriptor instead.
func (*MembershipEntry) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{9}
}

func (x *MembershipEntry) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *MembershipEntry) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MembershipEntry) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *MembershipEntry) GetRole() uint32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *MembershipEntry) GetAddedBy() string {
	if x != nil {
		return x.AddedBy
	}
	return ""
}

func (x *MembershipEntry) GetAddedAtMs() int64 {
	if x != nil {
		return x.AddedAtMs
	}
	return 0
}

func (x *MembershipEntry) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

// MembershipGossip carries a network's roster for anti-entropy convergence; a receiver
// verifies each entry against its trust root before accepting or re-propagating it.
type MembershipGossip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	Entries       []*MembershipEntry     `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipGossip) Reset() {
	*x = MembershipGossip{}
	mi := &file_wire_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipGossip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipGossip) ProtoMessage() {}

func (x *MembershipGossip) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipGossip.ProtoReflect.Descriptor instead.
func (*MembershipGossip) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{10}
}

func (x *MembershipGossip) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *MembershipGossip) GetEntries() []*MembershipEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// SyncReceipt is a replica's acknowledgement that it has converged a folder to the
// owner's snapshot_root at (index_epoch_id, high_water_sequence). The owner records one
// per replica so "last synced" is queryable and tombstone reaping can wait for every
// replica to pass the deletion. It rides the mutually-authenticated session, so peer
// identity is the session's, not a field here.
type SyncReceipt struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FolderId          string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	SnapshotRoot      []byte                 `protobuf:"bytes,2,opt,name=snapshot_root,json=snapshotRoot,proto3" json:"snapshot_root,omitempty"`
	IndexEpochId      uint64                 `protobuf:"varint,3,opt,name=index_epoch_id,json=indexEpochId,proto3" json:"index_epoch_id,omitempty"`
	HighWaterSequence int64                  `protobuf:"varint,4,opt,name=high_water_sequence,json=highWaterSequence,proto3" json:"high_water_sequence,omitempty"`
	SyncedMs          int64                  `protobuf:"varint,5,opt,name=synced_ms,json=syncedMs,proto3" json:"synced_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncReceipt) Reset() {
	*x = SyncReceipt{}
	mi := &file_wire_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncReceipt) ProtoMessage() {}

func (x *SyncReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncReceipt.ProtoReflect.Descriptor instead.
func (*SyncReceipt) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{11}
}

func (x *SyncReceipt) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *SyncReceipt) GetSnapshotRoot() []byte {
	if x != nil {
		return x.SnapshotRoot
	}
	return nil
}

func (x *SyncReceipt) GetIndexEpochId() uint64 {
	if x != nil {
		return x.IndexEpochId
	}
	return 0
}

func (x *SyncReceipt) GetHighWaterSequence() int64 {
	if x != nil {
		return x.HighWaterSequence
	}
	return 0
}

func (x *SyncReceipt) GetSyncedMs() int64 {
	if x != nil {
		return x.SyncedMs
	}
	return 0
}

// Ping is the idle-timer keepalive.
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_wire_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{12}
}

// Close requests a graceful shutdown.
type Close struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Close) Reset() {
	*x = Close{}
	mi := &file_wire_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Close) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Close) ProtoMessage() {}

func (x *Close) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Close.ProtoReflect.Descriptor instead.
func (*Close) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{13}
}

func (x *Close) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_wire_proto protoreflect.FileDescriptor

const file_wire_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"wire.proto\x12\rtrove.wire.v1\"\xac\x01\n" +
	"\x05Hello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12.\n" +
	"\x13wire_format_version\x18\x02 \x01(\rR\x11wireFormatVersion\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vclient_name\x18\x04 \x01(\tR\n" +
	"clientName\x12%\n" +
	"\x0eclient_version\x18\x05 \x01(\tR\rclientVersion\">\n" +
	"\x06Header\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12 \n" +
	"\vcompression\x18\x02 \x01(\rR\vcompression\"\xdb\x01\n" +
	"\x06Folder\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\x12:\n" +
	"\vfolder_type\x18\x02 \x01(\x0e2\x19.trove.wire.v1.FolderTypeR\n" +
	"folderType\x12\x1c\n" +
	"\tencrypted\x18\x03 \x01(\bR\tencrypted\x12$\n" +
	"\x0eindex_epoch_id\x18\x04 \x01(\x04R\findexEpochId\x12.\n" +
	"\x13high_water_sequence\x18\x05 \x01(\x03R\x11highWaterSequenceJ\x04\b\x06\x10\a\"F\n" +
	"\rNetworkConfig\x12/\n" +
	"\afolders\x18\x01 \x03(\v2\x15.trove.wire.v1.FolderR\afoldersJ\x04\b\x03\x10\x04\"\xa7\x01\n" +
	"\rFolderSummary\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\x12#\n" +
	"\rsnapshot_root\x18\x02 \x01(\fR\fsnapshotRoot\x12$\n" +
	"\x0eindex_epoch_id\x18\x03 \x01(\x04R\findexEpochId\x12.\n" +
	"\x13high_water_sequence\x18\x04 \x01(\x03R\x11highWaterSequence\"\xa9\x01\n" +
	"\x0fManifestRequest\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\x12$\n" +
	"\x0eindex_epoch_id\x18\x02 \x01(\x04R\findexEpochId\x12%\n" +
	"\x0esince_sequence\x18\x03 \x01(\x03R\rsinceSequence\x12,\n" +
	"\x12since_chunk_offset\x18\x04 \x01(\x03R\x10sinceChunkOffset\"=\n" +
	"\bChunkRef\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\fR\achunkId\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x03R\x06length\"\xed\x02\n" +
	"\x0eRemoteManifest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\rR\x04kind\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12%\n" +
	"\x0esymlink_target\x18\x04 \x01(\tR\rsymlinkTarget\x12/\n" +
	"\x06chunks\x18\x05 \x03(\v2\x17.trove.wire.v1.ChunkRefR\x06chunks\x12\x1f\n" +
	"\vmanifest_id\x18\x06 \x01(\fR\n" +
	"manifestId\x12%\n" +
	"\x0eversion_vector\x18\a \x01(\fR\rversionVector\x12%\n" +
	"\x0eowner_sequence\x18\b \x01(\x03R\rownerSequence\x12\x18\n" +
	"\adeleted\x18\t \x01(\bR\adeleted\x12\x1d\n" +
	"\n" +
	"deleted_ms\x18\n" +
	" \x01(\x03R\tdeletedMs\x12\x1f\n" +
	"\vmore_chunks\x18\v \x01(\bR\n" +
	"moreChunks\"\x92\x02\n" +
	"\rManifestDelta\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\x12$\n" +
	"\x0eindex_epoch_id\x18\x02 \x01(\x04R\findexEpochId\x12.\n" +
	"\x13high_water_sequence\x18\x03 \x01(\x03R\x11highWaterSequence\x12;\n" +
	"\tmanifests\x18\x04 \x03(\v2\x1d.trove.wire.v1.RemoteManifestR\tmanifests\x12\x1a\n" +
	"\bcomplete\x18\x05 \x01(\bR\bcomplete\x125\n" +
	"\x17high_water_chunk_offset\x18\x06 \x01(\x03R\x14highWaterChunkOffset\"\xc9\x01\n" +
	"\x0fMembershipEntry\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12\x12\n" +
	"\x04role\x18\x04 \x01(\rR\x04role\x12\x19\n" +
	"\badded_by\x18\x05 \x01(\tR\aaddedBy\x12\x1e\n" +
	"\vadded_at_ms\x18\x06 \x01(\x03R\taddedAtMs\x12\x10\n" +
	"\x03sig\x18\a \x01(\fR\x03sig\"k\n" +
	"\x10MembershipGossip\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x128\n" +
	"\aentries\x18\x02 \x03(\v2\x1e.trove.wire.v1.MembershipEntryR\aentries\"\xc2\x01\n" +
	"\vSyncReceipt\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\x12#\n" +
	"\rsnapshot_root\x18\x02 \x01(\fR\fsnapshotRoot\x12$\n" +
	"\x0eindex_epoch_id\x18\x03 \x01(\x04R\findexEpochId\x12.\n" +
	"\x13high_water_sequence\x18\x04 \x01(\x03R\x11highWaterSequence\x12\x1b\n" +
	"\tsynced_ms\x18\x05 \x01(\x03R\bsyncedMs\"\x06\n" +
	"\x04Ping\"\x1f\n" +
	"\x05Close\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason*\x86\x01\n" +
	"\n" +
	"FolderType\x12\x1c\n" +
	"\x18FOLDER_TYPE_SEND_RECEIVE\x10\x00\x12\x19\n" +
	"\x15FOLDER_TYPE_SEND_ONLY\x10\x01\x12\x1c\n" +
	"\x18FOLDER_TYPE_RECEIVE_ONLY\x10\x02\x12!\n" +
	"\x1dFOLDER_TYPE_RECEIVE_ENCRYPTED\x10\x03B@Z>github.com/GhentiLabs/Trove/client/internal/wire/wirepb;wirepbb\x06proto3"

var (
	file_wire_proto_rawDescOnce sync.Once
	file_wire_proto_rawDescData []byte
)

func file_wire_proto_rawDescGZIP() []byte {
	file_wire_proto_rawDescOnce.Do(func() {
		file_wire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wire_proto_rawDesc), len(file_wire_proto_rawDesc)))
	})
	return file_wire_proto_rawDescData
}

var file_wire_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_wire_proto_goTypes = []any{
	(FolderType)(0),          // 0: trove.wire.v1.FolderType
	(*Hello)(nil),            // 1: trove.wire.v1.Hello
	(*Header)(nil),           // 2: trove.wire.v1.Header
	(*Folder)(nil),           // 3: trove.wire.v1.Folder
	(*NetworkConfig)(nil),    // 4: trove.wire.v1.NetworkConfig
	(*FolderSummary)(nil),    // 5: trove.wire.v1.FolderSummary
	(*ManifestRequest)(nil),  // 6: trove.wire.v1.ManifestRequest
	(*ChunkRef)(nil),         // 7: trove.wire.v1.ChunkRef
	(*RemoteManifest)(nil),   // 8: trove.wire.v1.RemoteManifest
	(*ManifestDelta)(nil),    // 9: trove.wire.v1.ManifestDelta
	(*MembershipEntry)(nil),  // 10: trove.wire.v1.MembershipEntry
	(*MembershipGossip)(nil), // 11: trove.wire.v1.MembershipGossip
	(*SyncReceipt)(nil),      // 12: trove.wire.v1.SyncReceipt
	(*Ping)(nil),             // 13: trove.wire.v1.Ping
	(*Close)(nil),            // 14: trove.wire.v1.Close
}
var file_wire_proto_depIdxs = []int32{
	0,  // 0: trove.wire.v1.Folder.folder_type:type_name -> trove.wire.v1.FolderType
	3,  // 1: trove.wire.v1.NetworkConfig.folders:type_name -> trove.wire.v1.Folder
	7,  // 2: trove.wire.v1.RemoteManifest.chunks:type_name -> trove.wire.v1.ChunkRef
	8,  // 3: trove.wire.v1.ManifestDelta.manifests:type_name -> trove.wire.v1.RemoteManifest
	10, // 4: trove.wire.v1.MembershipGossip.entries:type_name -> trove.wire.v1.MembershipEntry
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_wire_proto_init() }
func file_wire_proto_init() {
	if File_wire_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wire_proto_rawDesc), len(file_wire_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_proto_goTypes,
		DependencyIndexes: file_wire_proto_depIdxs,
		EnumInfos:         file_wire_proto_enumTypes,
		MessageInfos:      file_wire_proto_msgTypes,
	}.Build()
	File_wire_proto = out.File
	file_wire_proto_goTypes = nil
	file_wire_proto_depIdxs = nil
}
